/* 
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.831
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The VideoPublicRepresentation class
    /// </summary>
    [DataContract]
    public partial class VideoPublicRepresentation :  IEquatable<VideoPublicRepresentation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VideoPublicRepresentation" /> class.
        /// </summary>
        /// <param name="Id">The id of the video.</param>
        /// <param name="UserId">The is of the owning user.</param>
        /// <param name="Status">The status of the video.</param>
        /// <param name="Name">The name of the video.</param>
        /// <param name="Description">A description of the video.</param>
        /// <param name="ThumbUrl">The url of the thumbnail for the video.</param>
        /// <param name="VideoUrls">Urls to different formats of the video.</param>
        /// <param name="ShortUrl">The url to use to link to the video.</param>
        /// <param name="Height">The height of the video in pixels.</param>
        /// <param name="Width">The width of the video in pixels.</param>
        /// <param name="UploadDate">The date the video was uploaded.</param>
        public VideoPublicRepresentation(string Id = default(string), string UserId = default(string), string Status = default(string), string Name = default(string), string Description = default(string), string ThumbUrl = default(string), List<string> VideoUrls = default(List<string>), string ShortUrl = default(string), int? Height = default(int?), int? Width = default(int?), string UploadDate = default(string))
        {
            this.Id = Id;
            this.UserId = UserId;
            this.Status = Status;
            this.Name = Name;
            this.Description = Description;
            this.ThumbUrl = ThumbUrl;
            this.VideoUrls = VideoUrls;
            this.ShortUrl = ShortUrl;
            this.Height = Height;
            this.Width = Width;
            this.UploadDate = UploadDate;
        }
        
        /// <summary>
        /// The id of the video
        /// </summary>
        /// <value>The id of the video</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The is of the owning user
        /// </summary>
        /// <value>The is of the owning user</value>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public string UserId { get; set; }

        /// <summary>
        /// The status of the video
        /// </summary>
        /// <value>The status of the video</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// The name of the video
        /// </summary>
        /// <value>The name of the video</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// A description of the video
        /// </summary>
        /// <value>A description of the video</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// The url of the thumbnail for the video
        /// </summary>
        /// <value>The url of the thumbnail for the video</value>
        [DataMember(Name="thumbUrl", EmitDefaultValue=false)]
        public string ThumbUrl { get; set; }

        /// <summary>
        /// Urls to different formats of the video
        /// </summary>
        /// <value>Urls to different formats of the video</value>
        [DataMember(Name="videoUrls", EmitDefaultValue=false)]
        public List<string> VideoUrls { get; set; }

        /// <summary>
        /// The url to use to link to the video
        /// </summary>
        /// <value>The url to use to link to the video</value>
        [DataMember(Name="shortUrl", EmitDefaultValue=false)]
        public string ShortUrl { get; set; }

        /// <summary>
        /// The height of the video in pixels
        /// </summary>
        /// <value>The height of the video in pixels</value>
        [DataMember(Name="height", EmitDefaultValue=false)]
        public int? Height { get; set; }

        /// <summary>
        /// The width of the video in pixels
        /// </summary>
        /// <value>The width of the video in pixels</value>
        [DataMember(Name="width", EmitDefaultValue=false)]
        public int? Width { get; set; }

        /// <summary>
        /// The date the video was uploaded
        /// </summary>
        /// <value>The date the video was uploaded</value>
        [DataMember(Name="uploadDate", EmitDefaultValue=false)]
        public string UploadDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VideoPublicRepresentation {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ThumbUrl: ").Append(ThumbUrl).Append("\n");
            sb.Append("  VideoUrls: ").Append(VideoUrls).Append("\n");
            sb.Append("  ShortUrl: ").Append(ShortUrl).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  UploadDate: ").Append(UploadDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VideoPublicRepresentation);
        }

        /// <summary>
        /// Returns true if VideoPublicRepresentation instances are equal
        /// </summary>
        /// <param name="input">Instance of VideoPublicRepresentation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VideoPublicRepresentation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.ThumbUrl == input.ThumbUrl ||
                    (this.ThumbUrl != null &&
                    this.ThumbUrl.Equals(input.ThumbUrl))
                ) && 
                (
                    this.VideoUrls == input.VideoUrls ||
                    this.VideoUrls != null &&
                    this.VideoUrls.SequenceEqual(input.VideoUrls)
                ) && 
                (
                    this.ShortUrl == input.ShortUrl ||
                    (this.ShortUrl != null &&
                    this.ShortUrl.Equals(input.ShortUrl))
                ) && 
                (
                    this.Height == input.Height ||
                    (this.Height != null &&
                    this.Height.Equals(input.Height))
                ) && 
                (
                    this.Width == input.Width ||
                    (this.Width != null &&
                    this.Width.Equals(input.Width))
                ) && 
                (
                    this.UploadDate == input.UploadDate ||
                    (this.UploadDate != null &&
                    this.UploadDate.Equals(input.UploadDate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.ThumbUrl != null)
                    hashCode = hashCode * 59 + this.ThumbUrl.GetHashCode();
                if (this.VideoUrls != null)
                    hashCode = hashCode * 59 + this.VideoUrls.GetHashCode();
                if (this.ShortUrl != null)
                    hashCode = hashCode * 59 + this.ShortUrl.GetHashCode();
                if (this.Height != null)
                    hashCode = hashCode * 59 + this.Height.GetHashCode();
                if (this.Width != null)
                    hashCode = hashCode * 59 + this.Width.GetHashCode();
                if (this.UploadDate != null)
                    hashCode = hashCode * 59 + this.UploadDate.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
