/* 
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OAuthClient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OAuthClientTests
    {
        // TODO uncomment below to declare an instance variable for OAuthClient
        //private OAuthClient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OAuthClient
            //instance = new OAuthClient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OAuthClient
        /// </summary>
        [Test]
        public void OAuthClientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OAuthClient
            //Assert.IsInstanceOfType<OAuthClient> (instance, "variable 'instance' is a OAuthClient");
        }

        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Test]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ClientSecret'
        /// </summary>
        [Test]
        public void ClientSecretTest()
        {
            // TODO unit test for the property 'ClientSecret'
        }
        /// <summary>
        /// Test the property 'GrantsAllowed'
        /// </summary>
        [Test]
        public void GrantsAllowedTest()
        {
            // TODO unit test for the property 'GrantsAllowed'
        }
        /// <summary>
        /// Test the property 'OwningUserId'
        /// </summary>
        [Test]
        public void OwningUserIdTest()
        {
            // TODO unit test for the property 'OwningUserId'
        }
        /// <summary>
        /// Test the property 'RedirectUri'
        /// </summary>
        [Test]
        public void RedirectUriTest()
        {
            // TODO unit test for the property 'RedirectUri'
        }

    }

}
