/* 
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.831
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PromptMonthlyPerformance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PromptMonthlyPerformanceTests
    {
        // TODO uncomment below to declare an instance variable for PromptMonthlyPerformance
        //private PromptMonthlyPerformance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PromptMonthlyPerformance
            //instance = new PromptMonthlyPerformance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PromptMonthlyPerformance
        /// </summary>
        [Test]
        public void PromptMonthlyPerformanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PromptMonthlyPerformance
            //Assert.IsInstanceOfType<PromptMonthlyPerformance> (instance, "variable 'instance' is a PromptMonthlyPerformance");
        }


        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'UserBatchListsIdHelper'
        /// </summary>
        [Test]
        public void UserBatchListsIdHelperTest()
        {
            // TODO unit test for the property 'UserBatchListsIdHelper'
        }
        /// <summary>
        /// Test the property 'PromptIdHelper'
        /// </summary>
        [Test]
        public void PromptIdHelperTest()
        {
            // TODO unit test for the property 'PromptIdHelper'
        }

    }

}
